version: "3"
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_PASSWORD: example
