version: '3'
services:
  db:
    container_name: truth-or-action.db
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}

  migration:
    image: oleksiygontarpersonal/truth-or-action-bot:latest
    command: npm run prod:migration:run
    env_file: .env
    depends_on:
      - db
  
  bot:
    image: oleksiygontarpersonal/truth-or-action-bot:latest
    env_file: .env
    depends_on:
      - db
